// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HeavyMetal",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "HeavyMetal",
            targets: ["AppModule"],
            bundleIdentifier: "com.otabuzzman.heavymetal.ipados",
            teamIdentifier: "28FV44657B",
            displayVersion: "1.0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .weights),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
